general:
  experiment_name: thresholds_exp
  seed: 7

data:
  train_path: data/raw/train.csv
  test_path: data/raw/test.csv

target:
  column: Survived

features:
  numerical:
    - Age
    - SibSp
    - Parch
    - Fare
    - FamilySize
    - IsAlone
#    - TicketGroupSize
#    - FarePerPerson
#    - IsChild
  categorical:
    - Pclass
    - Sex
    - Embarked
    - Title
    - Deck
#    - SexPclass
    - AgeBand
#    - FamilyCategory
#    - PclassAgeBand
    - TicketPrefix

validation:
  n_splits: 5
  shuffle: true

evaluation:
  primary_metric: accuracy
  metrics:
    - accuracy
    - precision
    - recall
    - roc_auc
  plots:
    enabled: false
    roc_curve: true
    pr_curve: true

explainability:
  enabled: false
  sample_size: 800
  generic:
    max_evals: 500
    max_samples: 200

submission:
  enabled: true
  id_column: PassengerId
  top_n_models: 2

threshold_tuning:
  enabled: true

models:
  logistic_regression:
    enabled: true
    params:
      C: 1.0
      max_iter: 1000

  knn:
    enabled: false
    params:
      n_neighbors: 5

  svm:
    enabled: true
    params:
      C: 1.0
      kernel: rbf
      probability: true

  random_forest:
    enabled: false
    params:
      random_state: ${general.seed}

  xgboost:
    enabled: true
    params:
      random_state: ${general.seed}
      n_jobs: 1
      n_estimators: 500
      learning_rate: 0.03
    early_stopping:
      enabled: true
      validation_fraction: 0.2
      patience: 50
      random_state: ${general.seed}

  catboost:
    enabled: true
    params:
      iterations: 500
      learning_rate: 0.03
      depth: 6
      loss_function: Logloss
      verbose: false
      random_seed: ${general.seed}
    early_stopping:
      enabled: false
      validation_fraction: 0.2
      patience: 50
      random_state: ${general.seed}

  neural_network:
    enabled: true
    params:
      learning_rate: 0.01
      epochs: 50
      batch_size: 64
      log_every_n_epochs: 20
      random_state: ${general.seed}
      device: mps
      num_threads: 1
    early_stopping:
      enabled: true
      validation_fraction: 0.2
      patience: 10
      min_delta: 0.0001

output:
  experiments_dir: outputs/experiments
  submission_dir: outputs/submissions
